// Auto-generated by auto_update.py. Do not edit this file manually.
// Data is rebuilt from issues/ and files/.

window.SITE_CONFIG = {
  "siteTitle": "東門國小學生家長會",
  "academicYear": 114-115,
  "school": "臺北市中正區東門國民小學"
};

window.BOOK_SETTINGS = [
  {
    "id": "114-03",
    "title": "第三期",
    "date": "2026.06",
    "cover": "../issues/114-03/cover.webp",
    "pages": [
      "../issues/114-03/page-1.webp",
      "../issues/114-03/page-2.webp"
    ],
    "pageNumbers": [
      1,
      2
    ]
  },
  {
    "id": "114-02",
    "title": "第二期",
    "date": "2026.03",
    "cover": "../issues/114-02/cover.webp",
    "pages": [
      "../issues/114-02/page-1.webp",
      "../issues/114-02/page-2.webp",
      "../issues/114-02/page-3.webp",
      "../issues/114-02/page-4.webp",
      "../issues/114-02/page-5.webp",
      "../issues/114-02/page-6.webp"
    ],
    "pageNumbers": [
      1,
      2,
      3,
      4,
      5,
      6
    ]
  },
  {
    "id": "114-01",
    "title": "創刊號",
    "date": "2025.11",
    "cover": "../issues/114-01/cover.webp",
    "pages": [
      "../issues/114-01/page-1.webp",
      "../issues/114-01/page-2.webp",
      "../issues/114-01/page-3.webp",
      "../issues/114-01/page-4.webp",
      "../issues/114-01/page-5.webp",
      "../issues/114-01/page-6.webp",
      "../issues/114-01/page-7.webp",
      "../issues/114-01/page-8.webp",
      "../issues/114-01/page-9.webp",
      "../issues/114-01/page-10.webp",
      "../issues/114-01/page-11.webp",
      "../issues/114-01/page-12.webp",
      "../issues/114-01/page-13.webp",
      "../issues/114-01/page-14.webp",
      "../issues/114-01/page-15.webp"
    ],
    "pageNumbers": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15
    ]
  }
];

window.MINUTES_DATABASE = [
  {
    "date": "2025-09-17",
    "rocDate": "114/9/17",
    "academicYear": 114,
    "type": "代",
    "typeName": "會員代表大會",
    "number": 1,
    "title": "114學年度第一次會員代表大會會議紀錄",
    "file": "../files/minutes/20250917_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%9C%83%E5%93%A1%E4%BB%A3%E8%A1%A8%E5%A4%A7%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2025-10-02",
    "rocDate": "114/10/2",
    "academicYear": 114,
    "type": "家",
    "typeName": "家長委員會",
    "number": 1,
    "title": "114學年度第一次家長委員會會議記錄",
    "file": "../files/minutes/20251002_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%AE%B6%E9%95%B7%E5%A7%94%E5%93%A1%E6%9C%83%E6%9C%83%E8%AD%B0%E8%A8%98%E9%8C%84.pdf"
  },
  {
    "date": "2025-10-02",
    "rocDate": "114/10/2",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 1,
    "title": "114學年度第一次常委會會議紀錄",
    "file": "../files/minutes/20251002_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%80%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2025-10-08",
    "rocDate": "114/10/8",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 2,
    "title": "114學年度第二次常委會會議紀錄",
    "file": "../files/minutes/20251008_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%BA%8C%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2025-11-07",
    "rocDate": "114/11/7",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 3,
    "title": "114學年度第三次常委會會議紀錄",
    "file": "../files/minutes/20251107_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%89%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2025-12-09",
    "rocDate": "114/12/9",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 4,
    "title": "114學年度第四次常委會會議紀錄",
    "file": "../files/minutes/20251209_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E5%9B%9B%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-01-05",
    "rocDate": "115/1/5",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 5,
    "title": "114學年度第五次常委會會議紀錄",
    "file": "../files/minutes/20260105_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%BA%94%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-01-12",
    "rocDate": "115/1/12",
    "academicYear": 114,
    "type": "家",
    "typeName": "家長委員會",
    "number": 2,
    "title": "114學年度第二次家長委員會會議記錄",
    "file": "../files/minutes/20260112_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%BA%8C%E6%AC%A1%E5%AE%B6%E9%95%B7%E5%A7%94%E5%93%A1%E6%9C%83%E6%9C%83%E8%AD%B0%E8%A8%98%E9%8C%84.pdf"
  },
  {
    "date": "2026-01-26",
    "rocDate": "115/1/26",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 6,
    "title": "114學年度第六次常委會會議紀錄",
    "file": "../files/minutes/20260126_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E5%85%AD%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-03-04",
    "rocDate": "115/3/4",
    "academicYear": 114,
    "type": "家",
    "typeName": "家長委員會",
    "number": 3,
    "title": "114學年度第三次家長委員會會議紀錄",
    "file": "../files/minutes/20260304_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%89%E6%AC%A1%E5%AE%B6%E9%95%B7%E5%A7%94%E5%93%A1%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-03-30",
    "rocDate": "115/3/30",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 7,
    "title": "114學年度第七次常委會會議紀錄",
    "file": "../files/minutes/20260330_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B8%83%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-05-06",
    "rocDate": "115/5/6",
    "academicYear": 114,
    "type": "家",
    "typeName": "家長委員會",
    "number": 4,
    "title": "114學年度第四次家長委員會會議紀錄",
    "file": "../files/minutes/20260506_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E5%9B%9B%E6%AC%A1%E5%AE%B6%E9%95%B7%E5%A7%94%E5%93%A1%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-06-01",
    "rocDate": "115/6/1",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 8,
    "title": "114學年度第八次常委會會議紀錄",
    "file": "../files/minutes/20260601_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E5%85%AB%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-07-01",
    "rocDate": "115/7/1",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 9,
    "title": "114學年度第九次常委會會議紀錄",
    "file": "../files/minutes/20260701_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%B9%9D%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  },
  {
    "date": "2026-08-27",
    "rocDate": "115/8/27",
    "academicYear": 114,
    "type": "家",
    "typeName": "家長委員會",
    "number": 5,
    "title": "114學年度第五次家長委員會會議記錄",
    "file": "../files/minutes/20260827_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E4%BA%94%E6%AC%A1%E5%AE%B6%E9%95%B7%E5%A7%94%E5%93%A1%E6%9C%83%E6%9C%83%E8%AD%B0%E8%A8%98%E9%8C%84.pdf"
  },
  {
    "date": "2026-09-23",
    "rocDate": "115/9/23",
    "academicYear": 114,
    "type": "常",
    "typeName": "常委會",
    "number": 10,
    "title": "114學年度第十次常委會會議紀錄",
    "file": "../files/minutes/20260923_114%E5%AD%B8%E5%B9%B4%E5%BA%A6%E7%AC%AC%E5%8D%81%E6%AC%A1%E5%B8%B8%E5%A7%94%E6%9C%83%E6%9C%83%E8%AD%B0%E7%B4%80%E9%8C%84.pdf"
  }
];

window.DONORS_DATABASE = [
  {
    "id": "general",
    "year": "114-1學年度",
    "title": "一般會務捐款",
    "file": "../files/donors/114-1%E5%AE%B6%E9%95%B7%E6%9C%83%E6%8D%90%E6%AC%BE%E8%8A%B3%E5%90%8D%E9%8C%84_%E4%B8%80%E8%88%AC%E6%9C%83%E5%8B%99%E6%8D%90%E6%AC%BE_%E6%88%AA%E8%87%B320251231.jpg",
    "asOf": "2025-12-31"
  },
  {
    "id": "toilet",
    "year": "114-1學年度",
    "title": "廁所香香專案指定捐款",
    "file": "../files/donors/114-1%E5%AE%B6%E9%95%B7%E6%9C%83%E6%8D%90%E6%AC%BE%E8%8A%B3%E5%90%8D%E9%8C%84_%E5%BB%81%E6%89%80%E9%A6%99%E9%A6%99%E6%8C%87%E5%AE%9A%E6%8D%90%E6%AC%BE_%E6%88%AA%E8%87%B320251231.jpg",
    "asOf": "2025-12-31"
  },
  {
    "id": "misc",
    "year": "114-1學年度",
    "title": "各項指定捐款",
    "file": "../files/donors/114-1%E5%AE%B6%E9%95%B7%E6%9C%83%E6%8D%90%E6%AC%BE%E8%8A%B3%E5%90%8D%E9%8C%84_%E5%90%84%E9%A0%85%E6%8C%87%E5%AE%9A%E6%8D%90%E6%AC%BE_%E6%88%AA%E8%87%B320251231.jpg",
    "asOf": "2025-12-31"
  }
];

window.RULES_DATABASE = [
  {
    "title": "組織章程",
    "file": "../files/rules/%E7%B5%84%E7%B9%94%E7%AB%A0%E7%A8%8B.pdf"
  },
  {
    "title": "資訊服務網站之設置目的及管理辦法",
    "file": "../files/rules/%E8%B3%87%E8%A8%8A%E6%9C%8D%E5%8B%99%E7%B6%B2%E7%AB%99%E4%B9%8B%E8%A8%AD%E7%BD%AE%E7%9B%AE%E7%9A%84%E5%8F%8A%E7%AE%A1%E7%90%86%E8%BE%A6%E6%B3%95.pdf"
  },
  {
    "title": "選舉罷免辦法",
    "file": "../files/rules/%E9%81%B8%E8%88%89%E7%BD%B7%E5%85%8D%E8%BE%A6%E6%B3%95.pdf"
  },
  {
    "title": "非現金物資捐贈處理原則",
    "file": "../files/rules/%E9%9D%9E%E7%8F%BE%E9%87%91%E7%89%A9%E8%B3%87%E6%8D%90%E8%B4%88%E8%99%95%E7%90%86%E5%8E%9F%E5%89%87.pdf"
  }
];
